#cloud-config
hostname: ${ci_hostname}
instance-id: ${ci_instance_id}
#fqdn: fio01.nokogerra.lab
write_files:
- path: /etc/sysctl.d/60-disable-ipv6.conf
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6=1
    net.ipv6.conf.default.disable_ipv6=1
#- path: /etc/apt/apt.conf.d/00-proxy
#  permissions: 0640
#  owner: root
#  content: |
#    Acquire::http { Proxy "http://example.com:8080"; };
#    Acquire::https { Proxy "http://example.com:8080"; };
#    Acquire::http::Pipeline-Depth "23";
#    Acquire::Languages "none";
runcmd:
- netplan --debug apply
- sysctl -w net.ipv6.conf.all.disable_ipv6=1
- sysctl -w net.ipv6.conf.default.disable_ipv6=1
timezone: Europe/Moscow
system_info:
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
disable_root: false
ssh_pwauth: yes
users:
  - default
  - name: ansible 
    gecos: ANSIBLE
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1vL6k5wsX2fGjtvKIegfR3+kiOLJw7t+tTzXcUFnEBH7p3LRgiVMu2+hAlOZazqpKjQVucOP02ZaHxQcb8D0c6Gp1AYdtZnUZjPF6Kufwn5ZMhk3LpS0qR/dnvl3Oxy7Vr9m8K/Rl1AaLOzHC34btPoFHcMoA+vE3F8+eDaf2rVPfnaR5RD0t4yIGmDgfkNHV8Bnx84bHWdkZnTv9C5sit2kEBA7fTi4WBiL51LwXpz9Eycxcr+iezk8alZthw+OEoxLX+u/z9ybBQ7unyC4ZPsfcl3D3TND8x7Euql1seV39Xcj7kJflOzEXs1Bj86oCOH78/R+PPJg28UwTDgiRn6iG7bqZG+lPtMNU1bgur6S4fTlFJQhG0g9i5oP7fhDdX3f9vcsnm81niBFyWvDC/+5mVR949IXrgyqF1FDoYSEcgRR/SeiLU41/2SmuRE2pgPJVJQegQyNKty9OYTt9FdApCc+aOEOZo0EI3aEmMoeH5X04KkiDrrAnY5RgAVs= ansible@s1-ans01
chpasswd:
  list: |
    default-user:$6$u4QdFzm8YjVbHnKG$alf5CvGcGBPKBaPDCthOnBV/YUGMkjLGdeT5oH3wDTvUYeLUBIT2Psv9kPPcPimB4wGB6PjH7CcEMgH/yJVXn0
    ansible:$6$ZSr6xuWPDoq0CnXk$c4C14Dr2RLjD9Tpd43Sxxyw8jNGecMQde9IvLFth9L0Fl4sreqlfGurfLK/qmZLJVqdpOOM2kCMy.fURTJgej.
    root:$6$ivG0b09UZ5SlF.WL$S9QS3s1QDgZBmDIoRdf1fb4I2dIOBvqrIgVMd5aPovS320rt5SCh7lKe5defzBydb26qleJ2DuiSty6jp89mS/
  expire: false
package_upgrade: true
package_reboot_if_required: true
power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi