---
- name: 'configure storage for fio test'
  hosts: fio
  tasks:
   - name: 'create PVs and VGs'
     community.general.lvg:
       vg: "{{ item.vg }}"
       pvs: "/dev/{{ item.disk }}"
     loop:
       - { vg: "{{ vg1 }}", disk: "{{ disk 1 }}" }
       - { vg: "{{ vg2 }}", disk: "{{ disk 2 }}" }  
   - name: 'create lvs'
     community.general.lvol:
       lv: "{{ item.lv }}"
       vg: "{{ item.vg }}"
       state: present
       shrink: false
       size: 100%FREE
     loop:
       - { vg: "{{ vg1 }}", lv: "{{ lv1 }}" }
       - { vg: "{{ vg2 }}", lv: "{{ lv2 }}" }  
   - name: 'create fs1'
     community.general.filesystem:
       dev: "/dev/mapper/{{ item }}"
       fstype: ext4
       state: present
     loop:
       - "{{ vg1 }}-{{ lv1 }}"
       - "{{ vg2 }}-{{ lv2 }}"
   - name: 'mount fs1'
     ansible.posix.mount:
       path: "/{{ item.lv }}"
       src: "/dev/mapper/{{ item.src }}"
       state: mounted
       fstype: ext4
     loop:
       - { lv: "{{ lv1 }}", src: "{{ vg1 }}-{{ lv1 }}" }
       - { lv: "{{ lv2 }}", src: "{{ vg2 }}-{{ lv2 }}" }
...
