---
- name: 'configure storage for fio test'
  hosts: fio
  tasks:
   - name: 'create PVs and VGs'
     community.general.lvg:
       vg: "{{ item.vg }}"
       pvs: "/dev/{{ item.pv }}"
     loop: "{{ storages }}"
   - name: 'create lvs'
     community.general.lvol:
       lv: "{{ item.lv }}"
       vg: "{{ item.vg }}"
       state: present
       shrink: false
       size: 100%FREE
     loop: "{{ storages }}"
   - name: 'create fs1'
     community.general.filesystem:
       dev: "/dev/mapper/{{ item.vg }}-{{ item.lv }}"
       fstype: ext4
       state: present
     loop: "{{ storages }}"
   - name: 'mount fs1'
     ansible.posix.mount:
       path: "/{{ item.lv }}"
       src: "/dev/mapper/{{ item.vg }}-{{ item.lv }}"
       state: mounted
       fstype: ext4
     loop: "{{ storages }}"
...
