---
- name: 'configure storage for fio test'
  hosts: fio
  tasks:
   - name: 'create PVs and VGs'
     community.general.lvg:
       vg: "{{ item.vg }}"
       pvs: "/dev/{{ item.pv }}"
     loop: "{{ storages }}"
   - name: 'create LVs'
     community.general.lvol:
       lv: "{{ item.lv }}"
       vg: "{{ item.vg }}"
       state: present
       shrink: false
       size: 100%FREE
     loop: "{{ storages }}"
   - name: 'create FSes'
     community.general.filesystem:
       dev: "/dev/mapper/{{ item.vg }}-{{ item.lv }}"
       fstype: ext4
       state: present
     loop: "{{ storages }}"
   - name: 'mount FSes'
     ansible.posix.mount:
       path: "/{{ item.lv }}"
       src: "/dev/mapper/{{ item.vg }}-{{ item.lv }}"
       state: mounted
       fstype: ext4
     loop: "{{ storages }}"
   - name: 'FSes permissions'
     ansible.builtin.file:
       path: "/{{ item.lv }}"
       state: directory
       recurse: true
       mode: 2666
       owner: "{{ main_user }}"
       group: "{{ main_group }}"
     loop: "{{ storages }}"     
...
