---
- name: 'configure storage for fio test'
  hosts: fio
  tasks:
   - name: 'create PV1 and VG1'
     community.general.lvg:
       vg: "{{ disk1 }}"
       pvs: "/dev/{{ disk1 }}"
   - name: 'create PV2 and VG2'
     community.general.lvg:
       vg: "{{ disk2 }}"
       pvs: "/dev/{{ disk2 }}"
   - name: 'create lv1'
     community.general.lvol:
       lv: "{{ disk1 }}"
       vg: "{{ disk1 }}"
       state: present
       shrink: false
       size: 100%FREE
   - name: 'create lv2'
     community.general.lvol:
       lv: "{{ disk2 }}"
       vg: "{{ disk2 }}"
       state: present
       shrink: false
       size: 100%FREE    
   - name: 'create fs1'
     community.general.filesystem:
       dev: "/dev/mapper/{{ disk1 }}-{{ disk1 }}"
       fstype: ext4
       state: present
   - name: 'create fs2'
     community.general.filesystem:
       dev: "/dev/mapper/{{ disk2 }}-{{ disk2 }}"
       fstype: ext4
       state: present
#   - name: 'create directory lvb'
#     file:
#       path: /lvb
#       state: directory
#   - name: 'create directory lvc'
#     file:
#       path: /lvc
#       state: directory
   - name: 'mount fs1'
     ansible.posix.mount:
       path: "/{{ disk1 }}"
       src: "/dev/mapper/{{ disk1 }}-{{ disk1 }}"
       state: mounted
       fstype: ext4
   - name: 'mount fs2'
     ansible.posix.mount:
       path: "/{{ disk2 }}"
       src: "/dev/mapper/{{ disk2 }}-{{ disk2 }}"
       state: mounted
       fstype: ext4
...
