---
- name: 'configure fio'
  hosts: fio
  tasks:
   - name: 'create fio directory'
     file:
       name: "{{ fio_dir }}"
       state: directory
   - name: 'install fio'
     ansible.builtin.apt:
       update_cache: true
       name: fio
       state: present
   - name: 'copy fio templates into fio directory'
     template:
       src: "{{ item.src }}"
       dest: "{{ fio_dir }}/{{ item.dst }}"
     loop:
       - { src: 'workload-profile1.j2', dest: 'workload-profile1.fio' }
       - { src: 'workload-profile2.j2', dest: 'workload-profile2.fio' }
       - { src: 'workload-profile3.j2', dest: 'workload-profile3.fio' }
       - { src: 'workload-profile4.j2', dest: 'workload-profile4.fio' }

...
