all:
  hosts:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    fio:
      hosts:
        fio[01:03]:
      vars:
        storages:
          - name: "sdb"
            pv: "sdb"
            vg: "vgb"
            lv: "lvb"
          - name: "sdc"
            pv: "sdc"
            vg: "vgc"
            lv: "lvc"
        #required to set the time format to get the iostat-cli usable output from iostat
        config_system_locale: "en_US.UTF-8"
        config_system_language: "en_US.UTF-8"
        # FIO common job vars
        templates_dir: "/home/ansible/fio-test/templates"
        fio_dir: "/fio"
        ramp_secs: "900"
        runtime_secs: "3600"
        test_file_size: "16g"
        # FIO workload-profile1 job vars
        rand_pct_wp1: 70
        bssplit_wp1: 64k/50:256k/15:32k/25:8k/10,64k/25:256k/5:32k/35:8k/35
        # FIO workload-profile2 job vars
        bs_wp2: 4k
        # FIO workload-profile3 job vars
        bs_wp3: 256k
        # FIO workload-profile4 job vars
        bs_wp4: 256k
        jobs:
          job1:
            name: "job1"
            file: "/lvb/job1"
            io_depth: "2"
            zonemode: "strided"
            zone_size_bytes: "3221225472"
            zone_range_bytes: "3221225472"
            zone_skip_bytes: "536870912"
          job2:
            name: "job2"
            file: "/lvc/job2"
            io_depth: "1"
            zonemode: strided
            zone_size_bytes: "3221225472"
            zone_range_bytes: "3221225472"
            zone_skip_bytes: "536870912"

            