---
#the description of jobs
#there will be as many jobs in a fio job file as described here
#this example creates relation: single lvol - single job - single file - multiple outstanding I/O per job
jobs:
  job1:
    name: "job1"
    file: "/lvb/job1"
    io_depth: "2"
    zonemode: "strided"
    zone_size_bytes: "32212254720"
    zone_range_bytes: "32212254720"
    zone_skip_bytes: "10737418240"
  job2:
    name: "job2"
    file: "/lvc/job2"
    io_depth: "1"
    zonemode: strided
    zone_size_bytes: "32212254720"
    zone_range_bytes: "32212254720"
    zone_skip_bytes: "10737418240"
...