#this is just a list of workload profiles (names of j2 templates), which will be used in the repeatable fio-run-internal play
#e.g. to run only 2 fio runs with workload_profile1.j2 and workload_profile2.j2, just comment out 3-d and 4-th profiles.
workload_profiles:
  - workload_profile1.j2
  - workload_profile2.j2
  - workload_profile3.j2
  - workload_profile4.j2
layout_profile: workload_profile_layout.j2